### ISSUE TITLE
'ss03' does not take 'ss01' into account

### ISSUE THREAD

**Issue by dscorbett** [notofonts/lao#12]
### Font
NotoSansLaoLooped-Regular.otf

### Where the font came from, and when
Site: https://github.com/notofonts/lao/releases/tag/NotoSansLaoLooped-v1.001
Date: 2022-09-06

### Font version
Version 1.001

### Issue
'ss03' right-aligns tone marks before post-base vowels, except when there is a pre-base vowel. However, the check for pre-base vowels does not work if the base is U+0E88 LAO LETTER CO and 'ss01' is active.

### Character data
ເຈ່ະ
U+0EC0 LAO VOWEL SIGN E
U+0E88 LAO LETTER CO
U+0EC8 LAO TONE MAI EK
U+0EB0 LAO VOWEL SIGN A

### Screenshot
![ເຈ່ະ](https://user-images.githubusercontent.com/1124347/188682891-774563c9-41d5-4200-a8c4-2028892c710e.png)

**Comment by ohbendy** [comment]
Thank you.

My commit notes got the wrong end of the stick, but I think the bug is fixed) ເຈ່ະ and ເຈ່ and ຈ່ະ are now appearing this way when both stylistic sets are applied:

![Screenshot 2023-01-11 at 13 56 45](https://user-images.githubusercontent.com/12471463/211824555-afd09750-1930-4bb4-a402-57824faec584.png)

**Comment by simoncozens** [comment]
Yes, this looks fixed now; thanks Ben!
